---
# This playbook contains common plays that will be run on all nodes.

- name: Add webmin repo 
  apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Add webmin mirror repo 
  apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
- name: Addkey webmin
  apt_key: url=http://www.webmin.com/jcameron-key.asc  state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
