# {{ ansible_managed }}
#FROM        debian:jessie
#FROM        stackbrew/ubuntu:14.04
FROM        jasongiedymin/ansible-base-ubuntu

# Volume can be accessed outside of container
VOLUME      [{{ docker_volume_directory }}]

MAINTAINER  Alban Andrieu "https://github.com/AlbanAndrieu"

ENV			DEBIAN_FRONTEND noninteractive
ENV         WEBMIN_HOME {{ webmin_base_dir }}

# Working dir
WORKDIR {{ docker_working_directory }}

# COPY
#COPY /workspace/users/albandri10/env/ansible/roles/jenkins-slave $WORKDIR

# ADD
ADD defaults $WORKDIR/defaults
ADD meta $WORKDIR/meta
ADD files $WORKDIR/files
#ADD handlers $WORKDIR/handlers
ADD tasks $WORKDIR/tasks
ADD templates $WORKDIR/templates
ADD vars $WORKDIR/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD playbook.yml $WORKDIR/playbook.yml -vvvv

# Execute
RUN         ansible-playbook $WORKDIR/playbook.yml -i $WORKDIR/hosts -c local

#RUN         apt-get update && \
#            apt-get install -y openssh-server openjdk-7-jre-headless
#RUN         useradd -m -s /bin/bash jenkins
#RUN         echo jenkins:jenkins | chpasswd
#RUN         mkdir -p /var/run/sshd
            
EXPOSE      22
ENTRYPOINT  ["/etc/init.d/webmin"]
#ENTRYPOINT ["java", "-jar", "{{ jenkins_home_dir }}/swarm-client-1.9-jar-with-dependencies.jar"]
CMD /usr/sbin/sshd -D
#CMD ["-g", "deamon off;"]
